IMP-270: impl proto
valitydev/provider-disputes-proto pull request #2
Opened 2024-07-11 11:03 UTC by karle0wne

2024-07-11 11:28 UTC, karle0wne commented on proto/provider-disputes.thrift
> +}
тут не уверен нужно ли changedAmount в принципе и где оно должно лежать

2024-07-11 11:28 UTC, karle0wne commented on proto/provider-disputes.thrift
> +}
+ ручка запроса статуса платежа (если получили success завершили, если fail то начинаем пулить и через N времени переходим к чек статусу диспута)
+ ручка создания диспута (в случае fail на платеже у провайдера)
+ ручка запроса статуса диспута (в случае кулдауна на проверке статуса платежа.  может быть не реализован у конкретной интеграции и кидать MethodNotSupported если отсутсвует такой флоу. в таком случае вся инфа должна быть на CheckTransactionStatus )

2024-07-11 11:28 UTC, karle0wne commented on proto/provider-disputes.thrift
> +}
ручка с получением колбека которую будет реализовывать dispute service и принимать ситуативно колбеки от провайдеров

2024-07-11 11:28 UTC, karle0wne commented on proto/provider-disputes.thrift
> +}
заранее не знаем какие параметры в колбек принесет провайдер поэтому все поля опциональны

2024-07-11 11:58 UTC, morningforsleeping commented
> create [provider] dispute -> check [provider] deposit status

местами надо поменять. Сначала спрашиваем в провайдере статус, затем идем создавать диспут

2024-07-16 01:20 UTC, morningforsleeping commented
> ```
> if [vality] deposit status == fail
предлагаю != success, чтобы из пендинга тоже можно было создавать диспут.

> ```
>   1 кейс - check [provider] deposit status = fail -> create [provider] dispute -> check [provider] deposit status = success (changed), ignore [provider] dispute status (= success) -> [vality] deposit status = success (changed) -> return [vality] dispute status = success
Тут все же не факт, что мы будем ждать статус депозита. Можем ждать и статус диспута. 
Я бы обозвал все же это как check [provider] dispute status

> ```
>   3 кейс - check [provider] deposit status = fail -> create [provider] dispute -> check [provider] deposit status = fail -> check [provider] dispute status = fail (trigger 'stop pooling') -> [vality] deposit status = fail -> return [vality] dispute status = fail
Непонятно, почему сначала идет опрос статуса депозита, потом диспута. Думаю это все же одно - check [provider] dispute status

2024-07-16 01:23 UTC, morningforsleeping commented on proto/provider-disputes.thrift
> +}
> тут не уверен нужно ли changedAmount в принципе и где оно должно лежать

нужно. Человек может заплатить или больше чем в заявке, или меньше. Чаще всего такие платежи ищутся через диспуты. 
Корректировки статусов лежат в dw.adjustment;
Корректировки сумм лежат в dw.payment_cash_change

2024-07-16 01:25 UTC, morningforsleeping commented on proto/provider-disputes.thrift
> +}
..amount
...reason/comment

2024-07-18 06:05 UTC, tolkonepiu requested changes

2024-07-18 06:05 UTC, tolkonepiu commented on proto/provider-disputes.thrift
> +    4: optional ID requisiteId
Что значает этот идентификатор?

2024-07-18 06:05 UTC, tolkonepiu commented on proto/provider-disputes.thrift
> +    2: required domain.ProxyOptions terminalOptions
Что это за поле и почему required, а invoiceId и paymentId нет? Что такое transactionId?

2024-07-18 06:05 UTC, tolkonepiu commented on proto/provider-disputes.thrift
> +struct Amount {
Можно было подтянуть готовую структуру, раз мы и так делаем include

2024-07-18 06:05 UTC, tolkonepiu commented on proto/provider-disputes.thrift
> +}
А если не знаем, то нужно ли описывать?

2024-07-18 06:05 UTC, tolkonepiu commented on proto/provider-disputes.thrift
> +}
По этим данным сервис будет делать корректировку в самой системе

2024-07-18 09:44 UTC, karle0wne commented on proto/provider-disputes.thrift
> +}
> А если не знаем, то нужно ли сейчас описывать?

тут имел ввиду, что у каждого провайдера свой набор полей, может не совпадать

2024-07-18 09:49 UTC, karle0wne commented on proto/provider-disputes.thrift
> +
> Непонятно, почему сначала идет опрос статуса депозита, потом диспута. Думаю это все же одно - check [provider] dispute status

переношу коммент сюда чтоб можно было писать в треде

а можешь плз тогда пояснить в чем суть проверять диспут статус? мы вроде обсуждали, что если статус депозита у провайдера success то статус диспута как и создание у провайдера не нужен, и мы меняем у себя его просто @morningforsleeping

2024-07-18 09:51 UTC, karle0wne commented on proto/provider-disputes.thrift
> +union Check {
это ок, а какой еще может быть Attachment , кроме чека? или это не важно тк мы сюда суем "некий" файл

2024-07-18 09:55 UTC, karle0wne commented on proto/provider-disputes.thrift
> +    3: domain.Failure failure
(не точно)

DisputeStatusResult это относится к бизнесовому статусу диспута
Failure все остальные неожиданные ситуации, например:

на схеме есть кейс 4, когда допустим провайдер не доступен и мы не можем обработать диспут, результат будет в Failure
![image](https://github.com/user-attachments/assets/a577f39f-3a96-437f-90cc-be1bd1deb175)

2024-07-18 09:56 UTC, tolkonepiu commented on proto/provider-disputes.thrift
> +union Check {
Тип документа не важен

2024-07-18 09:57 UTC, tolkonepiu commented on proto/provider-disputes.thrift
> +    3: domain.Failure failure
Не совсем понятно, как failure относится к диспуту

2024-07-18 10:05 UTC, karle0wne commented on proto/provider-disputes.thrift
> +    3: domain.Failure failure
а концептуально некое поле для ошибок норм? если failure из дамзеля это про платеж, но не относится, согласен

2024-07-18 10:14 UTC, karle0wne commented on proto/provider-disputes.thrift
> +    2: required domain.ProxyOptions terminalOptions
transactionId это айди платежа, созданный у провайдера который у нас кладется в https://github.com/valitydev/damsel/blob/6051aa94019df9cb1a5a90fa959cd19887c33a40/proto/domain.thrift#L94

по нему мы запрашиваем статус платежа до начала создания диспута , на случай если платеж уже в статусе success на стороне провайдера, тогда диспут не создаем

ProxyOptions опции терминала , которые мы обычно юзаем для авторизации запросов , в которых обычно лежит terminalId, shopId , access_key и тд

но иногда провайдеры при создании платежа не генерят свой transactionId , а юзают наш invoiceId и paymentId в виде invoiceFormatPaymentId , и эти параметры прокидываем на этот случай, если вдруг понадобится invoiceFormatPaymentId

2024-07-18 10:17 UTC, karle0wne commented on proto/provider-disputes.thrift
> +struct Amount {
ты имеешь ввиду заюзать domain.Cash вместо этого Amount? я чет не осознал, там внутри лежит CurrencyRef  и нет инфы по экспоненте
экспонента лежит в domain.Currency , но она избыточна, требует заполнения 4 поля, вроде в рамках диспутов без надобности

а в этой структуре оставил только нужное

2024-07-18 10:23 UTC, tolkonepiu commented on proto/provider-disputes.thrift
> +    3: domain.Failure failure
Не совсем понимаю итоговую схему, понятно для диступа должна быть причина, почему его зарежектили, но по протоколу пока не могу врубиться, кто куда ходит и что получает

2024-07-18 10:32 UTC, karle0wne commented on proto/provider-disputes.thrift
> +    3: domain.Failure failure
изначально это протокол , который будут реализовывать адаптеры, а вызывать кор сервис (dispute service) , прото нужен для формирования заявки на стороне провайдера, является результатом аналитики апишек провайдеров, что им нужно , чтоб создать диспут у себя
здесь описал смысл ручек https://github.com/valitydev/provider-disputes-proto/pull/2#discussion_r1673848361

пока вопрос про схему не понимаю, сначала нужна схема dispute service ?

2024-07-18 10:34 UTC, tolkonepiu commented on proto/provider-disputes.thrift
> +    3: domain.Failure failure
Давай опишем может быть rfc о том, как все будет работать?

2024-07-18 10:44 UTC, morningforsleeping commented on proto/provider-disputes.thrift
> +
Смотри, у тебя вот так описан 3 кейс:

(1) check [provider] deposit status = fail -> (2) create [provider] dispute -> (3) check [provider] deposit status = fail -> (4) check [provider] dispute status = fail (trigger 'stop pooling') -> (5) [vality] deposit status = fail -> (6) return [vality] dispute status = fail

на первом шаге опросили статус Депозита, убедились что он фейл. Далее на 2ом шаге поллим статус Диспута. Зачем на третьем шаге снова спрашиваем статус Депозита?

2024-07-18 10:45 UTC, karle0wne commented on proto/provider-disputes.thrift
> +    3: domain.Failure failure
да, давай этим займусь 

изначально решил первым делом  этот протокол создать, тк этого описания достаточно , чтоб с апи любого провайдера работать и чем мы ограничены
но этот мерж на rfc не влияет, просто тут как формат обсуждения части конкретики

как все будет работать опишу 🍏 

по поводу   формата в rfc не уверен , читал мотивацию Витали, он писал
> При описании RFC, к слову, как при описании любого архитектурного решения, нужно стараться отвечать на вопрос "почему", а не "как". Поэтому опускаем детали реализации, все детали реализации расписываем в задачах трекера.

то есть это же не подходит описание "как все будет работать" к рфс? 
в целом мне нейтрально где описать, но "как" это же скорее adr или ютрек?

2024-07-18 10:47 UTC, karle0wne commented on proto/provider-disputes.thrift
> +
тут (2) create [provider] dispute  типа создать диспут

2024-07-18 10:54 UTC, morningforsleeping commented on proto/provider-disputes.thrift
> +
Я думаю 3 и 4 можно объединить. Просто в некоторых интеграциях есть ручка опроса статуса диспута, а где-то надо опрашивать депозит. Кажется не надо и то и то опрашивать

2024-07-18 10:59 UTC, karle0wne commented on proto/provider-disputes.thrift
> +
то есть получается если у нас доступна опция пулить статус конкретно диспута то на депозит не смотрим?

2024-07-18 11:04 UTC, tolkonepiu commented on proto/provider-disputes.thrift
> +    3: domain.Failure failure
По формату я видел, что обычно уже расписывают как это будет работать. Тут возможно стоит уточнить у @vitaxa, но мне бы где-то увидеть всю картину сразу.

2024-07-18 11:14 UTC, karle0wne commented on proto/provider-disputes.thrift
> +    3: domain.Failure failure
> увидеть всю картину сразу

это уловил , будет

2024-07-18 11:17 UTC, morningforsleeping commented on proto/provider-disputes.thrift
> +
Да. Первично все равно спрашиваем статус депозита на всякий случай, а дальше пуллим что-то одно. Во всяком случае не вижу причин делать иначе

2024-08-07 09:24 UTC, echerniak approved these changes

2024-08-07 09:26 UTC, merged